---
title: "Decision Tree"
author: "Kiya Govek"
date: "1/16/2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# All of this is probably broken from moving on to Python. Just putting it here as an archive of what we tried in R with decision trees in case we want to come back


### Read in data
```{r}
evans <- read.csv("Evans_Room_Temp_and_Valve.csv")
names(evans)


```

### Get necessary library
```{r}
library(rpart)
```

### Split data smaller
```{r}
slice <- subset(evans, select=c(EV.RMG07.V, EV.RMG06.V))
#slice <- subset(evans, select=c(EV.HX2.HWST, OATEMP))
```

### Bin data
```{r}
library(mltools)
slice$EV.RMG07.V <- bin_data(slice$EV.RMG07.V, bins=5, binType = "quantile")
slice$EV.RMG06.V <- bin_data(slice$EV.RMG06.V, bins=5, binType = "quantile")

#slice$EV.RMG07.V <- cut(slice$EV.RMG07.V,breaks = 5)
#slice$EV.RMG06.V <- cut(slice$EV.RMG06.V,breaks = 5)
table(slice$EV.RMG07.V)
```

### Create tree
```{r}
test_tree = rpart(slice$EV.RMG07.V ~ slice$EV.RMG06.V, method = "class", data=slice)
summary(test_tree)
```

```{r}
plot(test_tree, uniform=TRUE, 
  	main="Classification of temperature")
text(test_tree, use.n=TRUE, all=TRUE, cex=.8)
```